### Step 1: Imports and Basing Preprocessing:

In [6]:
import pandas as pd
from sklearn.svm import SVR
from xgboost import XGBRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, r2_score
import optuna
from lightgbm import LGBMRegressor
from sklearn.ensemble import RandomForestRegressor
import mlflow
import mlflow.sklearn
import dagshub
import json
import pickle
from catboost import CatBoostRegressor

In [32]:
mlflow.set_tracking_uri("https://dagshub.com/PriyanshuMewal/delivery-time-prediction.mlflow")

dagshub.init(repo_owner='PriyanshuMewal', repo_name='delivery-time-prediction', mlflow=True)

mlflow.set_experiment("Experiment 4: Model Selection Without Missing Values")

Initialized MLflow to track repo "PriyanshuMewal/delivery-time-prediction"

Repository PriyanshuMewal/delivery-time-prediction initialized!

<Experiment: artifact_location='mlflow-artifacts:/0159417f09e1476798193b9381e1c2c4', creation_time=1771566150176, experiment_id='4', last_update_time=1771566150176, lifecycle_stage='active', name='Experiment 4: Model Selection Without Missing Values', tags={'mlflow.experimentKind': 'custom_model_development'}>

#### After Imputation:

In [33]:
train_df = pd.read_csv("/content/without_missing_values/train_df.csv")
test_df = pd.read_csv("/content/without_missing_values/test_df.csv")

In [14]:
train_df.head()

,age,ratings,pickup_time,distance,traffic,distance_type,order_time_of_day,weather_fog,weather_missing,weather_sandstorms,...,vehicle_type_motorcycle,vehicle_type_scooter,festival_yes,city_type_semi-urban,city_type_urban,multi_deliveries,condition,order_month,is_weekend,time
0,0.684211,0.84,0.846477,0.622989,1.0,2.0,1.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,1.0,0,3,0,1.671031
1,0.105263,0.80,0.564597,0.003331,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,2,3,0,-0.673246
2,0.894737,0.96,0.934564,0.002487,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,2,2,0,-0.673246
3,0.000000,0.84,0.921980,0.317057,3.0,1.0,2.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,1.0,2,3,0,-0.033898
4,0.315789,1.00,0.093960,0.318839,1.0,1.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,1.0,0,3,0,-0.033898

In [15]:
print(train_df.duplicated().sum())
test_df.duplicated().sum()

0

np.int64(0)

In [36]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29532 entries, 0 to 29531
Data columns (total 26 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Unnamed: 0                        29532 non-null  int64
 1   ord_cat__traffic                  29532 non-null  float64
 2   ord_cat__distance_type            29532 non-null  float64
 3   ord_cat__order_time_of_day        29532 non-null  float64
 4   nom_cat__weather_fog              29532 non-null  float64
 5   nom_cat__weather_sandstorms       29532 non-null  float64
 6   nom_cat__weather_stormy           29532 non-null  float64
 7   nom_cat__weather_sunny            29532 non-null  float64
 8   nom_cat__weather_windy            29532 non-null  float64
 9   nom_cat__order_type_drinks        29532 non-null  float64
 10  nom_cat__order_type_meal          29532 non-null  float64
 11  nom_cat__order_type_snack         29532 non-null  float64
 12  nom_cat__vehicle_type_motorcycle  29532 non-null  float64
 13  nom_cat__vehicle_type_scooter     29532 non-null  float64
 14  nom_cat__festival_yes             29532 non-null  float64
 15  nom_cat__city_type_semi-urban     29532 non-null  float64
 16  nom_cat__city_type_urban          29532 non-null  float64
 17  num__age                          29532 non-null  float64
 18  num__ratings                      29532 non-null  float64
 19  num__pickup_time                  29532 non-null  float64
 20  num__distance                     29532 non-null  float64
 21  remainder__condition              29532 non-null  int64
 22  remainder__multi_deliveries       29532 non-null  float64
 23  remainder__order_month            29532 non-null  int64
 24  remainder__is_weekend             29532 non-null  int64
 25  time                              29532 non-null  float64
dtypes: float64(22), int64(4)
memory usage: 5.9 MB

In [37]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7383 entries, 0 to 7382
Data columns (total 26 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Unnamed: 0                        7383 non-null   int64
 1   ord_cat__traffic                  7383 non-null   float64
 2   ord_cat__distance_type            7383 non-null   float64
 3   ord_cat__order_time_of_day        7383 non-null   float64
 4   nom_cat__weather_fog              7383 non-null   float64
 5   nom_cat__weather_sandstorms       7383 non-null   float64
 6   nom_cat__weather_stormy           7383 non-null   float64
 7   nom_cat__weather_sunny            7383 non-null   float64
 8   nom_cat__weather_windy            7383 non-null   float64
 9   nom_cat__order_type_drinks        7383 non-null   float64
 10  nom_cat__order_type_meal          7383 non-null   float64
 11  nom_cat__order_type_snack         7383 non-null   float64
 12  nom_cat__vehicle_type_motorcycle  7383 non-null   float64
 13  nom_cat__vehicle_type_scooter     7383 non-null   float64
 14  nom_cat__festival_yes             7383 non-null   float64
 15  nom_cat__city_type_semi-urban     7383 non-null   float64
 16  nom_cat__city_type_urban          7383 non-null   float64
 17  num__age                          7383 non-null   float64
 18  num__ratings                      7383 non-null   float64
 19  num__pickup_time                  7383 non-null   float64
 20  num__distance                     7383 non-null   float64
 21  remainder__condition              7383 non-null   int64
 22  remainder__multi_deliveries       7383 non-null   float64
 23  remainder__order_month            7383 non-null   int64
 24  remainder__is_weekend             7383 non-null   int64
 25  time                              7383 non-null   float64
dtypes: float64(22), int64(4)
memory usage: 1.5 MB

In [38]:
train_df.drop(columns=["Unnamed: 0"], inplace=True)
test_df.drop(columns=["Unnamed: 0"], inplace=True)

In [39]:
X_train = train_df.drop(columns=["time"])
X_test = test_df.drop(columns=["time"])

y_train = train_df["time"]
y_test = test_df["time"]

In [40]:
X_train.head()

,ord_cat__traffic,ord_cat__distance_type,ord_cat__order_time_of_day,nom_cat__weather_fog,nom_cat__weather_sandstorms,nom_cat__weather_stormy,nom_cat__weather_sunny,nom_cat__weather_windy,nom_cat__order_type_drinks,nom_cat__order_type_meal,...,nom_cat__city_type_semi-urban,nom_cat__city_type_urban,num__age,num__ratings,num__pickup_time,num__distance,remainder__condition,remainder__multi_deliveries,remainder__order_month,remainder__is_weekend
0,0.0,1.0,3.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.473684,0.84,0.714765,0.404182,1,0.0,4,1
1,2.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,0.631579,0.88,0.740772,0.243678,1,0.0,3,1
2,3.0,3.0,2.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,1.000000,0.64,0.573826,0.787364,0,0.0,4,0
3,2.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.263158,0.88,0.660235,0.236691,0,0.0,4,1
4,1.0,1.0,2.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,...,0.0,1.0,0.052632,0.92,0.360738,0.397584,0,1.0,3,1

In [42]:
y_test

0      -0.929363
1       1.633204
2       0.245147
3      -0.288721
4      -1.036137
          ...
7378    0.245147
7379   -1.142910
7380    0.245147
7381    2.060299
7382   -0.715816
Name: time, Length: 7383, dtype: float64

#### After removing missing values:

### Experimentation: Hyperparameter Tunning Over XGBoost, LightGBM, Catboost, Random Forest and SVM:

In [49]:
def objactive(trial, model):

    model_name = model().__class__.__name__

    param_dict = {}

    if model_name in [XGBRegressor().__class__.__name__, LGBMRegressor().__class__.__name__]:

        param_dict["n_estimators"] = trial.suggest_int("n_estimators", 50, 300)
        param_dict["max_depth"] = trial.suggest_int("max_depth", 3, 10)
        param_dict["learning_rate"] = trial.suggest_float("learning_rate", 1e-3, 1e-1, log=True)

    elif model_name == RandomForestRegressor().__class__.__name__:

        param_dict["n_estimators"] = trial.suggest_int("n_estimators", 50, 300)
        param_dict["max_depth"] = trial.suggest_int("max_depth", 3, 10)
        param_dict["min_samples_split"] = trial.suggest_int("min_samples_split", 2, 20)
        param_dict["min_samples_leaf"] = trial.suggest_int("min_samples_leaf", 1, 20)

    elif model_name == SVR().__class__.__name__:

        param_dict["C"] = trial.suggest_float("C", 0.1, 100, log=True)
        param_dict["epsilon"] = trial.suggest_float("epsilon", 0.005, 0.3)
        param_dict["gamma"] = trial.suggest_float("gamma", 1e-4, 1.0, log=True)

    if model_name == XGBRegressor().__class__.__name__:

        param_dict["tree_method"] = "hist"

    elif model_name == CatBoostRegressor().__class__.__name__:

        param_dict.update({"loss_function": "RMSE",
                          "iterations": trial.suggest_int("iterations", 500, 4000),
                          "learning_rate": trial.suggest_float("learning_rate", 1e-2, 1e-1, log=True),
                          "depth": trial.suggest_int("depth", 5, 9),
                          "l2_leaf_reg": trial.suggest_float("l2_leaf_reg", 3, 10),
                          "verbose": 0})


    model = model(**param_dict)

    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    mae = mean_absolute_error(y_true=y_test, y_pred=y_pred)
    r2 = r2_score(y_test, y_pred)

    trial.set_user_attr("r2", r2)
    return mae

In [50]:
best_params = {}

# Hyperparameter tunning over XGboost:
study = optuna.create_study(direction="minimize")
study.optimize(lambda trial: objactive(trial, XGBRegressor), n_trials=30)

best_params.update({"Xgboost": study.best_params})

[I 2026-02-20 06:19:50,409] A new study created in memory with name: no-name-d7142ef2-2bca-4cb8-a4c3-30e7bbaaed77
[I 2026-02-20 06:19:55,043] Trial 0 finished with value: 0.6827558548632389 and parameters: {'n_estimators': 99, 'max_depth': 3, 'learning_rate': 0.004240337536858211}. Best is trial 0 with value: 0.6827558548632389.
[I 2026-02-20 06:20:00,024] Trial 1 finished with value: 0.35671534759225265 and parameters: {'n_estimators': 137, 'max_depth': 4, 'learning_rate': 0.06699497687420111}. Best is trial 1 with value: 0.35671534759225265.
[I 2026-02-20 06:20:07,527] Trial 2 finished with value: 0.32533939452665966 and parameters: {'n_estimators': 274, 'max_depth': 9, 'learning_rate': 0.032911689792474746}. Best is trial 2 with value: 0.32533939452665966.
[I 2026-02-20 06:20:08,210] Trial 3 finished with value: 0.46900894087121886 and parameters: {'n_estimators': 224, 'max_depth': 4, 'learning_rate': 0.006912524778613582}. Best is trial 2 with value: 0.32533939452665966.
[I 2026-02-20 06:20:10,929] Trial 4 finished with value: 0.33343046389183334 and parameters: {'n_estimators': 300, 'max_depth': 9, 'learning_rate': 0.09673351550472185}. Best is trial 2 with value: 0.32533939452665966.
[I 2026-02-20 06:20:11,231] Trial 5 finished with value: 0.7490948136165021 and parameters: {'n_estimators': 86, 'max_depth': 4, 'learning_rate': 0.001650083500688972}. Best is trial 2 with value: 0.32533939452665966.
[I 2026-02-20 06:20:13,066] Trial 6 finished with value: 0.4619424944086889 and parameters: {'n_estimators': 184, 'max_depth': 9, 'learning_rate': 0.005022163999711272}. Best is trial 2 with value: 0.32533939452665966.
[I 2026-02-20 06:20:14,102] Trial 7 finished with value: 0.32705892874679454 and parameters: {'n_estimators': 106, 'max_depth': 9, 'learning_rate': 0.08375423816858923}. Best is trial 2 with value: 0.32533939452665966.
[I 2026-02-20 06:20:15,740] Trial 8 finished with value: 0.717589455492028 and parameters: {'n_estimators': 131, 'max_depth': 10, 'learning_rate': 0.0011665561181666848}. Best is trial 2 with value: 0.32533939452665966.
[I 2026-02-20 06:20:16,850] Trial 9 finished with value: 0.5177634157939437 and parameters: {'n_estimators': 149, 'max_depth': 8, 'learning_rate': 0.004766280720962989}. Best is trial 2 with value: 0.32533939452665966.
[I 2026-02-20 06:20:20,518] Trial 10 finished with value: 0.32913453092373135 and parameters: {'n_estimators': 294, 'max_depth': 7, 'learning_rate': 0.023506221231633533}. Best is trial 2 with value: 0.32533939452665966.
[I 2026-02-20 06:20:21,596] Trial 11 finished with value: 0.3321394361596812 and parameters: {'n_estimators': 234, 'max_depth': 6, 'learning_rate': 0.03436380874489448}. Best is trial 2 with value: 0.32533939452665966.
[I 2026-02-20 06:20:22,501] Trial 12 finished with value: 0.41146052283772233 and parameters: {'n_estimators': 57, 'max_depth': 10, 'learning_rate': 0.020786547947062896}. Best is trial 2 with value: 0.32533939452665966.
[I 2026-02-20 06:20:23,902] Trial 13 finished with value: 0.32659332279011416 and parameters: {'n_estimators': 245, 'max_depth': 7, 'learning_rate': 0.04475302501066167}. Best is trial 2 with value: 0.32533939452665966.
[I 2026-02-20 06:20:25,053] Trial 14 finished with value: 0.3313573221680357 and parameters: {'n_estimators': 260, 'max_depth': 6, 'learning_rate': 0.03842660486969792}. Best is trial 2 with value: 0.32533939452665966.
[I 2026-02-20 06:20:26,367] Trial 15 finished with value: 0.3453351002427191 and parameters: {'n_estimators': 216, 'max_depth': 7, 'learning_rate': 0.013169876487332888}. Best is trial 2 with value: 0.32533939452665966.
[I 2026-02-20 06:20:28,277] Trial 16 finished with value: 0.3270619978906832 and parameters: {'n_estimators': 266, 'max_depth': 8, 'learning_rate': 0.045451758161624195}. Best is trial 2 with value: 0.32533939452665966.
[I 2026-02-20 06:20:29,957] Trial 17 finished with value: 0.34114476067692384 and parameters: {'n_estimators': 194, 'max_depth': 8, 'learning_rate': 0.013368579057607435}. Best is trial 2 with value: 0.32533939452665966.
[I 2026-02-20 06:20:32,820] Trial 18 finished with value: 0.35601244294015644 and parameters: {'n_estimators': 256, 'max_depth': 5, 'learning_rate': 0.01953946333008628}. Best is trial 2 with value: 0.32533939452665966.
[I 2026-02-20 06:20:34,266] Trial 19 finished with value: 0.32848313903325166 and parameters: {'n_estimators': 276, 'max_depth': 7, 'learning_rate': 0.057251929476793396}. Best is trial 2 with value: 0.32533939452665966.
[I 2026-02-20 06:20:36,344] Trial 20 finished with value: 0.32624022385557433 and parameters: {'n_estimators': 240, 'max_depth': 8, 'learning_rate': 0.024054812482448413}. Best is trial 2 with value: 0.32533939452665966.
[I 2026-02-20 06:20:38,152] Trial 21 finished with value: 0.3264383899531228 and parameters: {'n_estimators': 237, 'max_depth': 8, 'learning_rate': 0.028104723038794133}. Best is trial 2 with value: 0.32533939452665966.
[I 2026-02-20 06:20:40,434] Trial 22 finished with value: 0.3253802381977751 and parameters: {'n_estimators': 205, 'max_depth': 9, 'learning_rate': 0.029400198447042065}. Best is trial 2 with value: 0.32533939452665966.
[I 2026-02-20 06:20:42,530] Trial 23 finished with value: 0.34945777988850135 and parameters: {'n_estimators': 204, 'max_depth': 9, 'learning_rate': 0.01133617476796547}. Best is trial 2 with value: 0.32533939452665966.
[I 2026-02-20 06:20:46,774] Trial 24 finished with value: 0.3371103316827367 and parameters: {'n_estimators': 166, 'max_depth': 10, 'learning_rate': 0.016380150245349685}. Best is trial 2 with value: 0.32533939452665966.
[I 2026-02-20 06:20:48,924] Trial 25 finished with value: 0.38141623424889104 and parameters: {'n_estimators': 213, 'max_depth': 9, 'learning_rate': 0.007667177235106308}. Best is trial 2 with value: 0.32533939452665966.
[I 2026-02-20 06:20:50,874] Trial 26 finished with value: 0.3265490353563993 and parameters: {'n_estimators': 269, 'max_depth': 8, 'learning_rate': 0.028621022196029505}. Best is trial 2 with value: 0.32533939452665966.
[I 2026-02-20 06:20:53,022] Trial 27 finished with value: 0.3271917559928222 and parameters: {'n_estimators': 162, 'max_depth': 10, 'learning_rate': 0.05994565037849449}. Best is trial 2 with value: 0.32533939452665966.
[I 2026-02-20 06:20:55,990] Trial 28 finished with value: 0.4893719699798107 and parameters: {'n_estimators': 285, 'max_depth': 9, 'learning_rate': 0.0027809961225352614}. Best is trial 2 with value: 0.32533939452665966.
[I 2026-02-20 06:20:59,641] Trial 29 finished with value: 0.3630112055494296 and parameters: {'n_estimators': 251, 'max_depth': 8, 'learning_rate': 0.008398261877388048}. Best is trial 2 with value: 0.32533939452665966.

In [51]:
# Hyperparameter tunning over LightGBM:
study = optuna.create_study(direction="minimize")
study.optimize(lambda trial: objactive(trial, LGBMRegressor), n_trials=30)

best_params.update({"lightgbm": study.best_params})

[I 2026-02-20 06:21:09,358] A new study created in memory with name: no-name-50e820d1-3bb7-4810-a487-da3465c096d5

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005473 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 607
[LightGBM] [Info] Number of data points in the train set: 29532, number of used features: 24
[LightGBM] [Info] Start training from score -0.000000
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[I 2026-02-20 06:21:10,413] Trial 0 finished with value: 0.39206563741911105 and parameters: {'n_estimators': 251, 'max_depth': 3, 'learning_rate': 0.03025999038955041}. Best is trial 0 with value: 0.39206563741911105.

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005211 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 607
[LightGBM] [Info] Number of data points in the train set: 29532, number of used features: 24
[LightGBM] [Info] Start training from score -0.000000

[I 2026-02-20 06:21:10,945] Trial 1 finished with value: 0.7391219373921404 and parameters: {'n_estimators': 84, 'max_depth': 9, 'learning_rate': 0.0014138529909454673}. Best is trial 0 with value: 0.39206563741911105.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003445 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 607
[LightGBM] [Info] Number of data points in the train set: 29532, number of used features: 24
[LightGBM] [Info] Start training from score -0.000000

[I 2026-02-20 06:21:11,795] Trial 2 finished with value: 0.33877811947881725 and parameters: {'n_estimators': 181, 'max_depth': 6, 'learning_rate': 0.036766212962920826}. Best is trial 2 with value: 0.33877811947881725.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003462 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 607
[LightGBM] [Info] Number of data points in the train set: 29532, number of used features: 24
[LightGBM] [Info] Start training from score -0.000000

[I 2026-02-20 06:21:12,174] Trial 3 finished with value: 0.6749941215404308 and parameters: {'n_estimators': 69, 'max_depth': 7, 'learning_rate': 0.0038275747419492722}. Best is trial 2 with value: 0.33877811947881725.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003511 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 607
[LightGBM] [Info] Number of data points in the train set: 29532, number of used features: 24
[LightGBM] [Info] Start training from score -0.000000
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[I 2026-02-20 06:21:13,033] Trial 4 finished with value: 0.3425445155797861 and parameters: {'n_estimators': 182, 'max_depth': 6, 'learning_rate': 0.03286313551456067}. Best is trial 2 with value: 0.33877811947881725.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003442 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 607
[LightGBM] [Info] Number of data points in the train set: 29532, number of used features: 24
[LightGBM] [Info] Start training from score -0.000000
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[I 2026-02-20 06:21:13,793] Trial 5 finished with value: 0.37339150499713447 and parameters: {'n_estimators': 207, 'max_depth': 4, 'learning_rate': 0.027304172032139484}. Best is trial 2 with value: 0.33877811947881725.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003507 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 607
[LightGBM] [Info] Number of data points in the train set: 29532, number of used features: 24
[LightGBM] [Info] Start training from score -0.000000
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[I 2026-02-20 06:21:14,403] Trial 6 finished with value: 0.6508398864007973 and parameters: {'n_estimators': 169, 'max_depth': 4, 'learning_rate': 0.0026335822601158475}. Best is trial 2 with value: 0.33877811947881725.

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003512 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 607
[LightGBM] [Info] Number of data points in the train set: 29532, number of used features: 24
[LightGBM] [Info] Start training from score -0.000000
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[I 2026-02-20 06:21:15,202] Trial 7 finished with value: 0.3932858185210538 and parameters: {'n_estimators': 276, 'max_depth': 3, 'learning_rate': 0.027219697478459405}. Best is trial 2 with value: 0.33877811947881725.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004085 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 607
[LightGBM] [Info] Number of data points in the train set: 29532, number of used features: 24
[LightGBM] [Info] Start training from score -0.000000
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[I 2026-02-20 06:21:16,288] Trial 8 finished with value: 0.33659167413728835 and parameters: {'n_estimators': 274, 'max_depth': 5, 'learning_rate': 0.05331010039419573}. Best is trial 8 with value: 0.33659167413728835.

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003725 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 607
[LightGBM] [Info] Number of data points in the train set: 29532, number of used features: 24
[LightGBM] [Info] Start training from score -0.000000
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[I 2026-02-20 06:21:16,822] Trial 9 finished with value: 0.3673894774228475 and parameters: {'n_estimators': 135, 'max_depth': 4, 'learning_rate': 0.049939177644589036}. Best is trial 8 with value: 0.33659167413728835.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003980 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 607
[LightGBM] [Info] Number of data points in the train set: 29532, number of used features: 24
[LightGBM] [Info] Start training from score -0.000000

[I 2026-02-20 06:21:17,821] Trial 10 finished with value: 0.32781687618355765 and parameters: {'n_estimators': 296, 'max_depth': 10, 'learning_rate': 0.09993445383690124}. Best is trial 10 with value: 0.32781687618355765.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003565 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 607
[LightGBM] [Info] Number of data points in the train set: 29532, number of used features: 24
[LightGBM] [Info] Start training from score -0.000000

[I 2026-02-20 06:21:18,820] Trial 11 finished with value: 0.32581785367268984 and parameters: {'n_estimators': 300, 'max_depth': 10, 'learning_rate': 0.08626312525560606}. Best is trial 11 with value: 0.32581785367268984.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003441 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 607
[LightGBM] [Info] Number of data points in the train set: 29532, number of used features: 24
[LightGBM] [Info] Start training from score -0.000000

[I 2026-02-20 06:21:19,840] Trial 12 finished with value: 0.3258124432735564 and parameters: {'n_estimators': 299, 'max_depth': 10, 'learning_rate': 0.08161965975787232}. Best is trial 12 with value: 0.3258124432735564.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003450 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 607
[LightGBM] [Info] Number of data points in the train set: 29532, number of used features: 24
[LightGBM] [Info] Start training from score -0.000000

[I 2026-02-20 06:21:21,217] Trial 13 finished with value: 0.36506608619244424 and parameters: {'n_estimators': 235, 'max_depth': 8, 'learning_rate': 0.010386455000429928}. Best is trial 12 with value: 0.3258124432735564.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005193 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 607
[LightGBM] [Info] Number of data points in the train set: 29532, number of used features: 24
[LightGBM] [Info] Start training from score -0.000000

[I 2026-02-20 06:21:22,629] Trial 14 finished with value: 0.328580663126221 and parameters: {'n_estimators': 299, 'max_depth': 10, 'learning_rate': 0.09125842734295625}. Best is trial 12 with value: 0.3258124432735564.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005270 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 607
[LightGBM] [Info] Number of data points in the train set: 29532, number of used features: 24
[LightGBM] [Info] Start training from score -0.000000

[I 2026-02-20 06:21:24,047] Trial 15 finished with value: 0.3567635031500597 and parameters: {'n_estimators': 236, 'max_depth': 9, 'learning_rate': 0.011034186023503723}. Best is trial 12 with value: 0.3258124432735564.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003461 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 607
[LightGBM] [Info] Number of data points in the train set: 29532, number of used features: 24
[LightGBM] [Info] Start training from score -0.000000

[I 2026-02-20 06:21:24,681] Trial 16 finished with value: 0.38228068790065245 and parameters: {'n_estimators': 111, 'max_depth': 8, 'learning_rate': 0.01784312859124304}. Best is trial 12 with value: 0.3258124432735564.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003429 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 607
[LightGBM] [Info] Number of data points in the train set: 29532, number of used features: 24
[LightGBM] [Info] Start training from score -0.000000

[I 2026-02-20 06:21:26,004] Trial 17 finished with value: 0.42937692249046644 and parameters: {'n_estimators': 260, 'max_depth': 9, 'learning_rate': 0.005074483876222}. Best is trial 12 with value: 0.3258124432735564.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003554 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 607
[LightGBM] [Info] Number of data points in the train set: 29532, number of used features: 24
[LightGBM] [Info] Start training from score -0.000000

[I 2026-02-20 06:21:26,899] Trial 18 finished with value: 0.3278080752515569 and parameters: {'n_estimators': 216, 'max_depth': 10, 'learning_rate': 0.06103844788638245}. Best is trial 12 with value: 0.3258124432735564.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003513 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 607
[LightGBM] [Info] Number of data points in the train set: 29532, number of used features: 24
[LightGBM] [Info] Start training from score -0.000000

[I 2026-02-20 06:21:28,348] Trial 19 finished with value: 0.3359501579320906 and parameters: {'n_estimators': 298, 'max_depth': 8, 'learning_rate': 0.016319639891202237}. Best is trial 12 with value: 0.3258124432735564.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003545 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 607
[LightGBM] [Info] Number of data points in the train set: 29532, number of used features: 24
[LightGBM] [Info] Start training from score -0.000000

[I 2026-02-20 06:21:29,008] Trial 20 finished with value: 0.3289164746266842 and parameters: {'n_estimators': 147, 'max_depth': 9, 'learning_rate': 0.0714156200159105}. Best is trial 12 with value: 0.3258124432735564.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003479 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 607
[LightGBM] [Info] Number of data points in the train set: 29532, number of used features: 24
[LightGBM] [Info] Start training from score -0.000000

[I 2026-02-20 06:21:29,878] Trial 21 finished with value: 0.3275942227638062 and parameters: {'n_estimators': 217, 'max_depth': 10, 'learning_rate': 0.06048294059060268}. Best is trial 12 with value: 0.3258124432735564.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003490 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 607
[LightGBM] [Info] Number of data points in the train set: 29532, number of used features: 24
[LightGBM] [Info] Start training from score -0.000000

[I 2026-02-20 06:21:30,954] Trial 22 finished with value: 0.32742630284267366 and parameters: {'n_estimators': 273, 'max_depth': 10, 'learning_rate': 0.04650661500402235}. Best is trial 12 with value: 0.3258124432735564.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003447 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 607
[LightGBM] [Info] Number of data points in the train set: 29532, number of used features: 24
[LightGBM] [Info] Start training from score -0.000000

[I 2026-02-20 06:21:32,065] Trial 23 finished with value: 0.32719297519519835 and parameters: {'n_estimators': 274, 'max_depth': 10, 'learning_rate': 0.04479018754760028}. Best is trial 12 with value: 0.3258124432735564.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003517 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 607
[LightGBM] [Info] Number of data points in the train set: 29532, number of used features: 24
[LightGBM] [Info] Start training from score -0.000000
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[I 2026-02-20 06:21:33,651] Trial 24 finished with value: 0.3304536112083315 and parameters: {'n_estimators': 250, 'max_depth': 7, 'learning_rate': 0.09873140111452469}. Best is trial 12 with value: 0.3258124432735564.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005530 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 607
[LightGBM] [Info] Number of data points in the train set: 29532, number of used features: 24
[LightGBM] [Info] Start training from score -0.000000

[I 2026-02-20 06:21:35,103] Trial 25 finished with value: 0.3284247732658877 and parameters: {'n_estimators': 283, 'max_depth': 9, 'learning_rate': 0.07354261242839433}. Best is trial 12 with value: 0.3258124432735564.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005909 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 607
[LightGBM] [Info] Number of data points in the train set: 29532, number of used features: 24
[LightGBM] [Info] Start training from score -0.000000

[I 2026-02-20 06:21:36,686] Trial 26 finished with value: 0.3366866758520555 and parameters: {'n_estimators': 257, 'max_depth': 8, 'learning_rate': 0.018766674404135913}. Best is trial 12 with value: 0.3258124432735564.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003723 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 607
[LightGBM] [Info] Number of data points in the train set: 29532, number of used features: 24
[LightGBM] [Info] Start training from score -0.000000

[I 2026-02-20 06:21:38,158] Trial 27 finished with value: 0.3761598419420892 and parameters: {'n_estimators': 284, 'max_depth': 10, 'learning_rate': 0.007141671019510455}. Best is trial 12 with value: 0.3258124432735564.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003653 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 607
[LightGBM] [Info] Number of data points in the train set: 29532, number of used features: 24
[LightGBM] [Info] Start training from score -0.000000

[I 2026-02-20 06:21:39,143] Trial 28 finished with value: 0.3288447175760593 and parameters: {'n_estimators': 230, 'max_depth': 9, 'learning_rate': 0.04781076992015097}. Best is trial 12 with value: 0.3258124432735564.

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003492 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 607
[LightGBM] [Info] Number of data points in the train set: 29532, number of used features: 24
[LightGBM] [Info] Start training from score -0.000000

[I 2026-02-20 06:21:40,238] Trial 29 finished with value: 0.3283656370865855 and parameters: {'n_estimators': 254, 'max_depth': 10, 'learning_rate': 0.036553832450192524}. Best is trial 12 with value: 0.3258124432735564.

In [52]:
# Hyperparameter tunning over RandomForestRegressor:
study = optuna.create_study(direction="minimize")
study.optimize(lambda trial: objactive(trial, RandomForestRegressor), n_trials=30)

best_params.update({"random_forest": study.best_params})

[I 2026-02-20 06:21:44,522] A new study created in memory with name: no-name-84e0054d-5b6a-43fa-aee2-8d7b654d301e
[I 2026-02-20 06:22:09,002] Trial 0 finished with value: 0.3895312746397602 and parameters: {'n_estimators': 267, 'max_depth': 8, 'min_samples_split': 6, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.3895312746397602.
[I 2026-02-20 06:22:25,480] Trial 1 finished with value: 0.48751808088359727 and parameters: {'n_estimators': 287, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 15}. Best is trial 0 with value: 0.3895312746397602.
[I 2026-02-20 06:22:36,655] Trial 2 finished with value: 0.39253016691558634 and parameters: {'n_estimators': 130, 'max_depth': 8, 'min_samples_split': 14, 'min_samples_leaf': 19}. Best is trial 0 with value: 0.3895312746397602.
[I 2026-02-20 06:22:56,954] Trial 3 finished with value: 0.3656765796431088 and parameters: {'n_estimators': 181, 'max_depth': 10, 'min_samples_split': 15, 'min_samples_leaf': 15}. Best is trial 3 with value: 0.3656765796431088.
[I 2026-02-20 06:23:00,884] Trial 4 finished with value: 0.5795529399495796 and parameters: {'n_estimators': 125, 'max_depth': 3, 'min_samples_split': 15, 'min_samples_leaf': 15}. Best is trial 3 with value: 0.3656765796431088.
[I 2026-02-20 06:23:07,277] Trial 5 finished with value: 0.5790686306105277 and parameters: {'n_estimators': 178, 'max_depth': 3, 'min_samples_split': 12, 'min_samples_leaf': 14}. Best is trial 3 with value: 0.3656765796431088.
[I 2026-02-20 06:23:20,372] Trial 6 finished with value: 0.363945460589315 and parameters: {'n_estimators': 113, 'max_depth': 10, 'min_samples_split': 16, 'min_samples_leaf': 9}. Best is trial 6 with value: 0.363945460589315.
[I 2026-02-20 06:23:35,704] Trial 7 finished with value: 0.36611123567678994 and parameters: {'n_estimators': 135, 'max_depth': 10, 'min_samples_split': 15, 'min_samples_leaf': 15}. Best is trial 6 with value: 0.363945460589315.
[I 2026-02-20 06:23:51,394] Trial 8 finished with value: 0.3912707799077434 and parameters: {'n_estimators': 173, 'max_depth': 8, 'min_samples_split': 16, 'min_samples_leaf': 13}. Best is trial 6 with value: 0.363945460589315.
[I 2026-02-20 06:24:07,215] Trial 9 finished with value: 0.4414159763876133 and parameters: {'n_estimators': 228, 'max_depth': 6, 'min_samples_split': 19, 'min_samples_leaf': 15}. Best is trial 6 with value: 0.363945460589315.
[I 2026-02-20 06:24:13,983] Trial 10 finished with value: 0.36381573251009824 and parameters: {'n_estimators': 62, 'max_depth': 10, 'min_samples_split': 9, 'min_samples_leaf': 6}. Best is trial 10 with value: 0.36381573251009824.
[I 2026-02-20 06:24:20,465] Trial 11 finished with value: 0.36383791350933553 and parameters: {'n_estimators': 53, 'max_depth': 10, 'min_samples_split': 9, 'min_samples_leaf': 6}. Best is trial 10 with value: 0.36381573251009824.
[I 2026-02-20 06:24:26,430] Trial 12 finished with value: 0.3736663488391116 and parameters: {'n_estimators': 61, 'max_depth': 9, 'min_samples_split': 8, 'min_samples_leaf': 5}. Best is trial 10 with value: 0.36381573251009824.
[I 2026-02-20 06:24:30,199] Trial 13 finished with value: 0.4146586756860651 and parameters: {'n_estimators': 50, 'max_depth': 7, 'min_samples_split': 2, 'min_samples_leaf': 7}. Best is trial 10 with value: 0.36381573251009824.
[I 2026-02-20 06:24:39,384] Trial 14 finished with value: 0.3727467919786185 and parameters: {'n_estimators': 88, 'max_depth': 9, 'min_samples_split': 9, 'min_samples_leaf': 2}. Best is trial 10 with value: 0.36381573251009824.
[I 2026-02-20 06:24:44,453] Trial 15 finished with value: 0.48343754923083637 and parameters: {'n_estimators': 88, 'max_depth': 5, 'min_samples_split': 11, 'min_samples_leaf': 6}. Best is trial 10 with value: 0.36381573251009824.
[I 2026-02-20 06:24:52,585] Trial 16 finished with value: 0.37430547677222953 and parameters: {'n_estimators': 83, 'max_depth': 9, 'min_samples_split': 9, 'min_samples_leaf': 11}. Best is trial 10 with value: 0.36381573251009824.
[I 2026-02-20 06:24:58,421] Trial 17 finished with value: 0.41544593788578743 and parameters: {'n_estimators': 69, 'max_depth': 7, 'min_samples_split': 5, 'min_samples_leaf': 4}. Best is trial 10 with value: 0.36381573251009824.
[I 2026-02-20 06:25:15,342] Trial 18 finished with value: 0.3637039725310149 and parameters: {'n_estimators': 155, 'max_depth': 10, 'min_samples_split': 11, 'min_samples_leaf': 9}. Best is trial 18 with value: 0.3637039725310149.
[I 2026-02-20 06:25:37,845] Trial 19 finished with value: 0.3736720258798909 and parameters: {'n_estimators': 221, 'max_depth': 9, 'min_samples_split': 12, 'min_samples_leaf': 9}. Best is trial 18 with value: 0.3637039725310149.
[I 2026-02-20 06:25:51,660] Trial 20 finished with value: 0.4406466741473811 and parameters: {'n_estimators': 207, 'max_depth': 6, 'min_samples_split': 7, 'min_samples_leaf': 11}. Best is trial 18 with value: 0.3637039725310149.
[I 2026-02-20 06:26:08,488] Trial 21 finished with value: 0.36327353148333 and parameters: {'n_estimators': 153, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 8}. Best is trial 21 with value: 0.36327353148333.
[I 2026-02-20 06:26:26,119] Trial 22 finished with value: 0.3635659539802183 and parameters: {'n_estimators': 152, 'max_depth': 10, 'min_samples_split': 11, 'min_samples_leaf': 8}. Best is trial 21 with value: 0.36327353148333.
[I 2026-02-20 06:26:41,175] Trial 23 finished with value: 0.37422660385996337 and parameters: {'n_estimators': 153, 'max_depth': 9, 'min_samples_split': 13, 'min_samples_leaf': 9}. Best is trial 21 with value: 0.36327353148333.
[I 2026-02-20 06:26:54,220] Trial 24 finished with value: 0.3905565798400199 and parameters: {'n_estimators': 149, 'max_depth': 8, 'min_samples_split': 11, 'min_samples_leaf': 12}. Best is trial 21 with value: 0.36327353148333.
[I 2026-02-20 06:27:16,524] Trial 25 finished with value: 0.3636926745467022 and parameters: {'n_estimators': 196, 'max_depth': 10, 'min_samples_split': 11, 'min_samples_leaf': 8}. Best is trial 21 with value: 0.36327353148333.
[I 2026-02-20 06:27:36,023] Trial 26 finished with value: 0.37363387982623636 and parameters: {'n_estimators': 199, 'max_depth': 9, 'min_samples_split': 18, 'min_samples_leaf': 8}. Best is trial 21 with value: 0.36327353148333.
[I 2026-02-20 06:27:48,056] Trial 27 finished with value: 0.36280837503133206 and parameters: {'n_estimators': 106, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 3}. Best is trial 27 with value: 0.36280837503133206.
[I 2026-02-20 06:27:52,965] Trial 28 finished with value: 0.5406918560372775 and parameters: {'n_estimators': 108, 'max_depth': 4, 'min_samples_split': 3, 'min_samples_leaf': 1}. Best is trial 27 with value: 0.36280837503133206.
[I 2026-02-20 06:28:01,592] Trial 29 finished with value: 0.41542767348780785 and parameters: {'n_estimators': 110, 'max_depth': 7, 'min_samples_split': 6, 'min_samples_leaf': 3}. Best is trial 27 with value: 0.36280837503133206.

In [55]:
# Hyperparameter tunning over Catboost:
# study = optuna.create_study(direction="minimize")
study.optimize(lambda trial: objactive(trial, CatBoostRegressor), n_trials=10)

best_params.update({"catboost": study.best_params})

[I 2026-02-20 06:39:51,334] Trial 20 finished with value: 0.32407355075680405 and parameters: {'iterations': 3194, 'learning_rate': 0.01292170496928116, 'depth': 9, 'l2_leaf_reg': 5.752526342064876}. Best is trial 20 with value: 0.32407355075680405.
[I 2026-02-20 06:40:52,572] Trial 21 finished with value: 0.32422624955126655 and parameters: {'iterations': 3149, 'learning_rate': 0.012184054916136586, 'depth': 9, 'l2_leaf_reg': 5.694780504601955}. Best is trial 20 with value: 0.32407355075680405.
[I 2026-02-20 06:41:49,798] Trial 22 finished with value: 0.3246953002390611 and parameters: {'iterations': 3235, 'learning_rate': 0.012517332585823571, 'depth': 9, 'l2_leaf_reg': 5.485464159130496}. Best is trial 20 with value: 0.32407355075680405.
[I 2026-02-20 06:42:57,174] Trial 23 finished with value: 0.3242747980980478 and parameters: {'iterations': 2948, 'learning_rate': 0.012402701206708805, 'depth': 9, 'l2_leaf_reg': 4.308545867563107}. Best is trial 20 with value: 0.32407355075680405.
[I 2026-02-20 06:43:32,520] Trial 24 finished with value: 0.32417915647728723 and parameters: {'iterations': 3094, 'learning_rate': 0.011938384766591799, 'depth': 8, 'l2_leaf_reg': 4.319886003344216}. Best is trial 20 with value: 0.32407355075680405.
[I 2026-02-20 06:44:17,264] Trial 25 finished with value: 0.32559341270711806 and parameters: {'iterations': 3797, 'learning_rate': 0.018766055694531998, 'depth': 8, 'l2_leaf_reg': 4.1856657267840855}. Best is trial 20 with value: 0.32407355075680405.
[I 2026-02-20 06:44:48,030] Trial 26 finished with value: 0.32586852768424684 and parameters: {'iterations': 3528, 'learning_rate': 0.011369091330281772, 'depth': 7, 'l2_leaf_reg': 6.034350685765164}. Best is trial 20 with value: 0.32407355075680405.
[I 2026-02-20 06:45:21,578] Trial 27 finished with value: 0.3250694756278002 and parameters: {'iterations': 3005, 'learning_rate': 0.023130955881133945, 'depth': 8, 'l2_leaf_reg': 3.842059500207773}. Best is trial 20 with value: 0.32407355075680405.
[I 2026-02-20 06:46:04,226] Trial 28 finished with value: 0.3247541660557084 and parameters: {'iterations': 3658, 'learning_rate': 0.017109307005899167, 'depth': 8, 'l2_leaf_reg': 4.738193347422012}. Best is trial 20 with value: 0.32407355075680405.
[I 2026-02-20 06:46:56,603] Trial 29 finished with value: 0.324857205597753 and parameters: {'iterations': 3009, 'learning_rate': 0.011928021790673362, 'depth': 9, 'l2_leaf_reg': 5.641360536622635}. Best is trial 20 with value: 0.32407355075680405.

In [ ]:
# Hyperparameter tunning over SVM:
study = optuna.create_study(direction="minimize")
study.optimize(lambda trial: objactive(trial, SVR), n_trials=10)

best_params.update({"svm": study.best_params})

[I 2026-02-19 15:04:07,226] A new study created in memory with name: no-name-9ac3a97d-4b1e-4296-8f5f-3bed162f2431
[I 2026-02-19 15:07:35,212] Trial 0 finished with value: 0.3909910928553759 and parameters: {'C': 1.5999121008456296, 'epsilon': 0.027198370700621213, 'gamma': 0.13864829887964417}. Best is trial 0 with value: 0.3909910928553759.
[I 2026-02-19 15:08:51,835] Trial 1 finished with value: 0.4276625867931324 and parameters: {'C': 0.5737908631589849, 'epsilon': 0.010426425873897563, 'gamma': 0.03160137418109366}. Best is trial 0 with value: 0.3909910928553759.
[I 2026-02-19 15:09:48,111] Trial 2 finished with value: 0.511577126152768 and parameters: {'C': 6.204039879612022, 'epsilon': 0.22102457619176563, 'gamma': 0.0003278634675621763}. Best is trial 0 with value: 0.3909910928553759.
[W 2026-02-19 15:27:29,953] Trial 3 failed with parameters: {'C': 39.19056964604964, 'epsilon': 0.2218436774886583, 'gamma': 0.4379018157596946} because of the following error: KeyboardInterrupt().
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/optuna/study/_optimize.py", line 206, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "/tmp/ipython-input-73455761.py", line 3, in <lambda>
    study.optimize(lambda trial: objactive(trial, SVR), n_trials=15)
                                 ^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ipython-input-1546808795.py", line 50, in objactive
    model.fit(X_train, y_train)
  File "/usr/local/lib/python3.12/dist-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/svm/_base.py", line 258, in fit
    fit(X, y, sample_weight, solver_type, kernel, random_seed=seed)
  File "/usr/local/lib/python3.12/dist-packages/sklearn/svm/_base.py", line 336, in _dense_fit
    ) = libsvm.fit(
        ^^^^^^^^^^^
  File "_libsvm.pyx", line 263, in sklearn.svm._libsvm.fit
KeyboardInterrupt
[W 2026-02-19 15:27:29,957] Trial 3 failed with value None.

KeyboardInterrupt:

In [ ]:
best_params

In [ ]:
import json

with open("/content/best_params.json", mode="w") as file:
  json.dump(best_params, file, indent=4)

In [ ]:
with open("best_params.json", "r") as file:
    best_params = json.load(file)
best_params

{'Xgboost': {'n_estimators': 52, 'max_depth': 10, 'learning_rate': 0.1},
 'lightgbm': {'n_estimators': 300, 'max_depth': 10, 'learning_rate': 0.1},
 'random_forest': {'n_estimators': 245,
  'max_depth': 10,
  'min_samples_split': 12,
  'min_samples_leaf': 3},
 'svm': {'C': 0.7016805586928897,
  'epsilon': 0.09532961100132147,
  'gamma': 0.13703551969616495}}

In [56]:
def log_mlflow(model, X_train, y_train, X_test, y_test):

    with mlflow.start_run(run_name=model.__class__.__name__):

        parameters = {"model": model.__class__.__name__,
                      "Imputation": "droped"}

        # logging parameters:
        parameters.update(model.get_params())
        mlflow.log_params(parameters)

        # Train and evaluate model:
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)

        mae = mean_absolute_error(y_test, y_pred)
        r2 = r2_score(y_test, y_pred)

        # logging metrics:
        mlflow.log_metric("mean_absolute_error", mae)
        mlflow.log_metric("r2_score", r2)

        # log model:
        # signature = mlflow.models.infer_signature(X_test, y_pred)
        # mlflow.sklearn.log_model(model, signature=signature)

        # logging datasets:
        # mlflow.log_artifact("../data/interim/reddit_cleaned.csv")

        # Set tags:
        # mlflow.set_tag("Author", "Priyanshu Mewal")
        # mlflow.set_tag("Description", "Food delivery prediction using Iterative Imputer with max_iter=15.")
        # mlflow.set_tag("Experiment", "HP over iterative imputer")

In [57]:
for model_name, params in best_params.items():

    if model_name == "Xgboost":
       model = XGBRegressor(**params)
    elif model_name == "lightgbm":
        model = LGBMRegressor(**params)
    elif model_name == "random_forest":
        model = RandomForestRegressor(**params)
    elif model_name == "catboost":
        model = CatBoostRegressor(**params)
    else:
        model = SVR(**params)

    log_mlflow(model, X_train, y_train, X_test, y_test)

🏃 View run XGBRegressor at: https://dagshub.com/PriyanshuMewal/delivery-time-prediction.mlflow/#/experiments/4/runs/7c90050a5e8b4e549702a3b7cc167d41
🧪 View experiment at: https://dagshub.com/PriyanshuMewal/delivery-time-prediction.mlflow/#/experiments/4
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004163 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 607
[LightGBM] [Info] Number of data points in the train set: 29532, number of used features: 24
[LightGBM] [Info] Start training from score -0.000000
🏃 View run LGBMRegressor at: https://dagshub.com/PriyanshuMewal/delivery-time-prediction.mlflow/#/experiments/4/runs/b905167e8c9f43179fe9ed9c5e02dfa3
🧪 View experiment at: https://dagshub.com/PriyanshuMewal/delivery-time-prediction.mlflow/#/experiments/4
🏃 View run RandomForestRegressor at: https://dagshub.com/PriyanshuMewal/delivery-time-prediction.mlflow/#/experiments/4/runs/3bf3a555010a4a47a8a8606b3dfc8193
🧪 View experiment at: https://dagshub.com/PriyanshuMewal/delivery-time-prediction.mlflow/#/experiments/4
0:	learn: 0.9906323	total: 18.7ms	remaining: 59.8s
1:	learn: 0.9812588	total: 34.7ms	remaining: 55.3s
2:	learn: 0.9720941	total: 50.2ms	remaining: 53.4s
3:	learn: 0.9630065	total: 65.7ms	remaining: 52.4s
4:	learn: 0.9540595	total: 81.1ms	remaining: 51.7s
5:	learn: 0.9452515	total: 96.3ms	remaining: 51.2s
6:	learn: 0.9367733	total: 112ms	remaining: 50.9s
7:	learn: 0.9285892	total: 127ms	remaining: 50.7s
8:	learn: 0.9201767	total: 143ms	remaining: 50.5s
9:	learn: 0.9122991	total: 158ms	remaining: 50.3s
10:	learn: 0.9041066	total: 173ms	remaining: 50.2s
11:	learn: 0.8960788	total: 189ms	remaining: 50.1s
12:	learn: 0.8883819	total: 205ms	remaining: 50.2s
13:	learn: 0.8809797	total: 224ms	remaining: 50.8s
14:	learn: 0.8733193	total: 242ms	remaining: 51.2s
15:	learn: 0.8660722	total: 259ms	remaining: 51.4s
16:	learn: 0.8588432	total: 274ms	remaining: 51.3s
17:	learn: 0.8515596	total: 290ms	remaining: 51.2s
18:	learn: 0.8446130	total: 307ms	remaining: 51.3s
19:	learn: 0.8380893	total: 324ms	remaining: 51.4s
20:	learn: 0.8311148	total: 340ms	remaining: 51.4s
21:	learn: 0.8244409	total: 356ms	remaining: 51.3s
22:	learn: 0.8177401	total: 372ms	remaining: 51.2s
23:	learn: 0.8111021	total: 387ms	remaining: 51.2s
24:	learn: 0.8048373	total: 403ms	remaining: 51.1s
25:	learn: 0.7979093	total: 419ms	remaining: 51s
26:	learn: 0.7918454	total: 437ms	remaining: 51.3s
27:	learn: 0.7858067	total: 453ms	remaining: 51.2s
28:	learn: 0.7798768	total: 469ms	remaining: 51.1s
29:	learn: 0.7743215	total: 484ms	remaining: 51.1s
30:	learn: 0.7686885	total: 500ms	remaining: 51.1s
31:	learn: 0.7627982	total: 516ms	remaining: 51s
32:	learn: 0.7573040	total: 532ms	remaining: 50.9s
33:	learn: 0.7517417	total: 547ms	remaining: 50.9s
34:	learn: 0.7462118	total: 563ms	remaining: 50.8s
35:	learn: 0.7410343	total: 580ms	remaining: 50.9s
36:	learn: 0.7360524	total: 595ms	remaining: 50.8s
37:	learn: 0.7313833	total: 611ms	remaining: 50.8s
38:	learn: 0.7262086	total: 632ms	remaining: 51.1s
39:	learn: 0.7212724	total: 665ms	remaining: 52.5s
40:	learn: 0.7163940	total: 681ms	remaining: 52.4s
41:	learn: 0.7115456	total: 697ms	remaining: 52.3s
42:	learn: 0.7069587	total: 712ms	remaining: 52.2s
43:	learn: 0.7021909	total: 729ms	remaining: 52.2s
44:	learn: 0.6975437	total: 745ms	remaining: 52.1s
45:	learn: 0.6931443	total: 760ms	remaining: 52s
46:	learn: 0.6887742	total: 776ms	remaining: 52s
47:	learn: 0.6843374	total: 792ms	remaining: 51.9s
48:	learn: 0.6799671	total: 808ms	remaining: 51.9s
49:	learn: 0.6760171	total: 824ms	remaining: 51.8s
50:	learn: 0.6718607	total: 840ms	remaining: 51.7s
51:	learn: 0.6679472	total: 855ms	remaining: 51.7s
52:	learn: 0.6640981	total: 873ms	remaining: 51.7s
53:	learn: 0.6603685	total: 889ms	remaining: 51.7s
54:	learn: 0.6567606	total: 904ms	remaining: 51.6s
55:	learn: 0.6530109	total: 920ms	remaining: 51.5s
56:	learn: 0.6494153	total: 936ms	remaining: 51.5s
57:	learn: 0.6456120	total: 953ms	remaining: 51.5s
58:	learn: 0.6421294	total: 969ms	remaining: 51.5s
59:	learn: 0.6387131	total: 985ms	remaining: 51.4s
60:	learn: 0.6353638	total: 1s	remaining: 51.4s
61:	learn: 0.6321382	total: 1.01s	remaining: 51.3s
62:	learn: 0.6289137	total: 1.03s	remaining: 51.2s
63:	learn: 0.6257160	total: 1.05s	remaining: 51.2s
64:	learn: 0.6224421	total: 1.06s	remaining: 51.3s
65:	learn: 0.6194405	total: 1.09s	remaining: 51.6s
66:	learn: 0.6164962	total: 1.1s	remaining: 51.5s
67:	learn: 0.6133391	total: 1.12s	remaining: 51.5s
68:	learn: 0.6102736	total: 1.14s	remaining: 51.4s
69:	learn: 0.6075309	total: 1.15s	remaining: 51.4s
70:	learn: 0.6045403	total: 1.17s	remaining: 51.3s
71:	learn: 0.6020498	total: 1.18s	remaining: 51.3s
72:	learn: 0.5994502	total: 1.2s	remaining: 51.2s
73:	learn: 0.5966397	total: 1.21s	remaining: 51.2s
74:	learn: 0.5940179	total: 1.23s	remaining: 51.2s
75:	learn: 0.5914478	total: 1.25s	remaining: 51.2s
76:	learn: 0.5889602	total: 1.26s	remaining: 51.2s
77:	learn: 0.5864705	total: 1.28s	remaining: 51.2s
78:	learn: 0.5838163	total: 1.3s	remaining: 51.2s
79:	learn: 0.5814890	total: 1.31s	remaining: 51.2s
80:	learn: 0.5791437	total: 1.33s	remaining: 51.1s
81:	learn: 0.5769777	total: 1.34s	remaining: 51s
82:	learn: 0.5747760	total: 1.36s	remaining: 51s
83:	learn: 0.5726194	total: 1.38s	remaining: 50.9s
84:	learn: 0.5705584	total: 1.39s	remaining: 50.9s
85:	learn: 0.5685272	total: 1.41s	remaining: 50.8s
86:	learn: 0.5664569	total: 1.42s	remaining: 50.8s
87:	learn: 0.5643616	total: 1.44s	remaining: 50.8s
88:	learn: 0.5623366	total: 1.45s	remaining: 50.8s
89:	learn: 0.5604088	total: 1.47s	remaining: 50.7s
90:	learn: 0.5585942	total: 1.49s	remaining: 50.7s
91:	learn: 0.5567727	total: 1.5s	remaining: 50.7s
92:	learn: 0.5550910	total: 1.52s	remaining: 50.7s
93:	learn: 0.5533111	total: 1.53s	remaining: 50.7s
94:	learn: 0.5516647	total: 1.55s	remaining: 50.6s
95:	learn: 0.5498735	total: 1.57s	remaining: 50.6s
96:	learn: 0.5481819	total: 1.58s	remaining: 50.6s
97:	learn: 0.5465563	total: 1.6s	remaining: 50.5s
98:	learn: 0.5449775	total: 1.61s	remaining: 50.5s
99:	learn: 0.5433784	total: 1.63s	remaining: 50.4s
100:	learn: 0.5417912	total: 1.65s	remaining: 50.4s
101:	learn: 0.5402022	total: 1.68s	remaining: 50.8s
102:	learn: 0.5386717	total: 1.7s	remaining: 50.9s
103:	learn: 0.5372042	total: 1.71s	remaining: 50.9s
104:	learn: 0.5357625	total: 1.73s	remaining: 50.9s
105:	learn: 0.5343928	total: 1.74s	remaining: 50.8s
106:	learn: 0.5330765	total: 1.76s	remaining: 50.7s
107:	learn: 0.5312201	total: 1.77s	remaining: 50.7s
108:	learn: 0.5298529	total: 1.79s	remaining: 50.6s
109:	learn: 0.5285782	total: 1.8s	remaining: 50.6s
110:	learn: 0.5272572	total: 1.82s	remaining: 50.5s
111:	learn: 0.5259762	total: 1.83s	remaining: 50.5s
112:	learn: 0.5244847	total: 1.85s	remaining: 50.4s
113:	learn: 0.5233110	total: 1.86s	remaining: 50.4s
114:	learn: 0.5214457	total: 1.88s	remaining: 50.3s
115:	learn: 0.5202976	total: 1.89s	remaining: 50.3s
116:	learn: 0.5190714	total: 1.91s	remaining: 50.2s
117:	learn: 0.5178133	total: 1.93s	remaining: 50.3s
118:	learn: 0.5167631	total: 1.95s	remaining: 50.3s
119:	learn: 0.5156230	total: 1.96s	remaining: 50.2s
120:	learn: 0.5145997	total: 1.98s	remaining: 50.2s
121:	learn: 0.5133169	total: 1.99s	remaining: 50.1s
122:	learn: 0.5113668	total: 2s	remaining: 50.1s
123:	learn: 0.5102501	total: 2.02s	remaining: 50s
124:	learn: 0.5092410	total: 2.04s	remaining: 50s
125:	learn: 0.5081514	total: 2.05s	remaining: 49.9s
126:	learn: 0.5073073	total: 2.06s	remaining: 49.9s
127:	learn: 0.5062872	total: 2.08s	remaining: 49.8s
128:	learn: 0.5053402	total: 2.1s	remaining: 49.8s
129:	learn: 0.5045114	total: 2.11s	remaining: 49.8s
130:	learn: 0.5034816	total: 2.13s	remaining: 49.7s
131:	learn: 0.5019476	total: 2.14s	remaining: 49.8s
132:	learn: 0.5009137	total: 2.16s	remaining: 49.7s
133:	learn: 0.4994199	total: 2.18s	remaining: 49.7s
134:	learn: 0.4985594	total: 2.19s	remaining: 49.7s
135:	learn: 0.4977301	total: 2.21s	remaining: 49.6s
136:	learn: 0.4967004	total: 2.22s	remaining: 49.6s
137:	learn: 0.4958144	total: 2.24s	remaining: 49.6s
138:	learn: 0.4949653	total: 2.26s	remaining: 49.6s
139:	learn: 0.4941329	total: 2.27s	remaining: 49.6s
140:	learn: 0.4925223	total: 2.29s	remaining: 49.6s
141:	learn: 0.4918855	total: 2.3s	remaining: 49.5s
142:	learn: 0.4909604	total: 2.32s	remaining: 49.5s
143:	learn: 0.4895859	total: 2.33s	remaining: 49.4s
144:	learn: 0.4889167	total: 2.35s	remaining: 49.4s
145:	learn: 0.4879680	total: 2.37s	remaining: 49.4s
146:	learn: 0.4870554	total: 2.38s	remaining: 49.3s
147:	learn: 0.4858940	total: 2.4s	remaining: 49.3s
148:	learn: 0.4852135	total: 2.41s	remaining: 49.3s
149:	learn: 0.4845752	total: 2.42s	remaining: 49.2s
150:	learn: 0.4839452	total: 2.44s	remaining: 49.2s
151:	learn: 0.4833293	total: 2.46s	remaining: 49.1s
152:	learn: 0.4822783	total: 2.47s	remaining: 49.1s
153:	learn: 0.4817275	total: 2.49s	remaining: 49.1s
154:	learn: 0.4811653	total: 2.5s	remaining: 49s
155:	learn: 0.4805852	total: 2.52s	remaining: 49s
156:	learn: 0.4798830	total: 2.53s	remaining: 49s
157:	learn: 0.4784178	total: 2.55s	remaining: 48.9s
158:	learn: 0.4776186	total: 2.56s	remaining: 49s
159:	learn: 0.4766118	total: 2.58s	remaining: 49s
160:	learn: 0.4758312	total: 2.6s	remaining: 48.9s
161:	learn: 0.4750456	total: 2.61s	remaining: 48.9s
162:	learn: 0.4740981	total: 2.63s	remaining: 48.9s
163:	learn: 0.4736340	total: 2.64s	remaining: 48.8s
164:	learn: 0.4730691	total: 2.66s	remaining: 48.8s
165:	learn: 0.4724838	total: 2.68s	remaining: 48.9s
166:	learn: 0.4718452	total: 2.71s	remaining: 49.1s
167:	learn: 0.4706315	total: 2.73s	remaining: 49.1s
168:	learn: 0.4700086	total: 2.74s	remaining: 49.1s
169:	learn: 0.4695321	total: 2.76s	remaining: 49.1s
170:	learn: 0.4689758	total: 2.77s	remaining: 49.1s
171:	learn: 0.4686270	total: 2.79s	remaining: 49s
172:	learn: 0.4681811	total: 2.81s	remaining: 49s
173:	learn: 0.4670402	total: 2.82s	remaining: 49s
174:	learn: 0.4666137	total: 2.83s	remaining: 48.9s
175:	learn: 0.4655284	total: 2.85s	remaining: 48.9s
176:	learn: 0.4650501	total: 2.87s	remaining: 48.9s
177:	learn: 0.4641418	total: 2.88s	remaining: 48.8s
178:	learn: 0.4629911	total: 2.9s	remaining: 48.8s
179:	learn: 0.4626523	total: 2.91s	remaining: 48.8s
180:	learn: 0.4617895	total: 2.93s	remaining: 48.7s
181:	learn: 0.4613741	total: 2.94s	remaining: 48.7s
182:	learn: 0.4609446	total: 2.96s	remaining: 48.7s
183:	learn: 0.4606175	total: 2.97s	remaining: 48.6s
184:	learn: 0.4603139	total: 2.99s	remaining: 48.6s
185:	learn: 0.4595060	total: 3.01s	remaining: 48.6s
186:	learn: 0.4591462	total: 3.02s	remaining: 48.6s
187:	learn: 0.4587203	total: 3.04s	remaining: 48.6s
188:	learn: 0.4579482	total: 3.05s	remaining: 48.5s
189:	learn: 0.4574477	total: 3.07s	remaining: 48.5s
190:	learn: 0.4569714	total: 3.08s	remaining: 48.5s
191:	learn: 0.4562268	total: 3.1s	remaining: 48.4s
192:	learn: 0.4556791	total: 3.11s	remaining: 48.4s
193:	learn: 0.4547072	total: 3.13s	remaining: 48.4s
194:	learn: 0.4543734	total: 3.14s	remaining: 48.3s
195:	learn: 0.4535752	total: 3.16s	remaining: 48.3s
196:	learn: 0.4531958	total: 3.18s	remaining: 48.3s
197:	learn: 0.4527271	total: 3.2s	remaining: 48.4s
198:	learn: 0.4524282	total: 3.21s	remaining: 48.4s
199:	learn: 0.4516649	total: 3.23s	remaining: 48.3s
200:	learn: 0.4512604	total: 3.25s	remaining: 48.3s
201:	learn: 0.4506815	total: 3.26s	remaining: 48.3s
202:	learn: 0.4503913	total: 3.28s	remaining: 48.3s
203:	learn: 0.4501362	total: 3.29s	remaining: 48.2s
204:	learn: 0.4497423	total: 3.31s	remaining: 48.2s
205:	learn: 0.4492792	total: 3.32s	remaining: 48.2s
206:	learn: 0.4484312	total: 3.34s	remaining: 48.2s
207:	learn: 0.4476030	total: 3.35s	remaining: 48.1s
208:	learn: 0.4473721	total: 3.37s	remaining: 48.1s
209:	learn: 0.4469975	total: 3.38s	remaining: 48.1s
210:	learn: 0.4467152	total: 3.4s	remaining: 48.1s
211:	learn: 0.4465126	total: 3.42s	remaining: 48.1s
212:	learn: 0.4463326	total: 3.43s	remaining: 48s
213:	learn: 0.4461127	total: 3.45s	remaining: 48s
214:	learn: 0.4458824	total: 3.46s	remaining: 48s
215:	learn: 0.4456088	total: 3.48s	remaining: 48s
216:	learn: 0.4454308	total: 3.49s	remaining: 47.9s
217:	learn: 0.4447839	total: 3.51s	remaining: 47.9s
218:	learn: 0.4445529	total: 3.52s	remaining: 47.9s
219:	learn: 0.4443095	total: 3.54s	remaining: 47.8s
220:	learn: 0.4441294	total: 3.55s	remaining: 47.8s
221:	learn: 0.4437775	total: 3.57s	remaining: 47.8s
222:	learn: 0.4434913	total: 3.58s	remaining: 47.8s
223:	learn: 0.4431155	total: 3.6s	remaining: 47.7s
224:	learn: 0.4428024	total: 3.62s	remaining: 47.7s
225:	learn: 0.4426752	total: 3.63s	remaining: 47.7s
226:	learn: 0.4421451	total: 3.65s	remaining: 47.7s
227:	learn: 0.4418097	total: 3.66s	remaining: 47.6s
228:	learn: 0.4414670	total: 3.68s	remaining: 47.6s
229:	learn: 0.4410601	total: 3.69s	remaining: 47.6s
230:	learn: 0.4408916	total: 3.71s	remaining: 47.6s
231:	learn: 0.4406804	total: 3.74s	remaining: 47.8s
232:	learn: 0.4402313	total: 3.76s	remaining: 47.8s
233:	learn: 0.4398163	total: 3.77s	remaining: 47.7s
234:	learn: 0.4396411	total: 3.79s	remaining: 47.7s
235:	learn: 0.4395244	total: 3.79s	remaining: 47.5s
236:	learn: 0.4390540	total: 3.81s	remaining: 47.5s
237:	learn: 0.4388696	total: 3.83s	remaining: 47.5s
238:	learn: 0.4386893	total: 3.84s	remaining: 47.5s
239:	learn: 0.4385337	total: 3.86s	remaining: 47.5s
240:	learn: 0.4378973	total: 3.87s	remaining: 47.5s
241:	learn: 0.4377588	total: 3.89s	remaining: 47.4s
242:	learn: 0.4373861	total: 3.9s	remaining: 47.4s
243:	learn: 0.4370460	total: 3.92s	remaining: 47.4s
244:	learn: 0.4369282	total: 3.94s	remaining: 47.4s
245:	learn: 0.4366624	total: 3.95s	remaining: 47.4s
246:	learn: 0.4364005	total: 3.97s	remaining: 47.3s
247:	learn: 0.4361951	total: 3.98s	remaining: 47.3s
248:	learn: 0.4359984	total: 4s	remaining: 47.3s
249:	learn: 0.4358754	total: 4.01s	remaining: 47.2s
250:	learn: 0.4356955	total: 4.03s	remaining: 47.2s
251:	learn: 0.4354422	total: 4.04s	remaining: 47.2s
252:	learn: 0.4351613	total: 4.06s	remaining: 47.2s
253:	learn: 0.4349503	total: 4.07s	remaining: 47.2s
254:	learn: 0.4348234	total: 4.09s	remaining: 47.1s
255:	learn: 0.4346180	total: 4.1s	remaining: 47.1s
256:	learn: 0.4341556	total: 4.12s	remaining: 47.1s
257:	learn: 0.4338402	total: 4.13s	remaining: 47.1s
258:	learn: 0.4336112	total: 4.15s	remaining: 47s
259:	learn: 0.4334762	total: 4.17s	remaining: 47s
260:	learn: 0.4333253	total: 4.18s	remaining: 47s
261:	learn: 0.4330939	total: 4.2s	remaining: 47s
262:	learn: 0.4326759	total: 4.21s	remaining: 47s
263:	learn: 0.4321190	total: 4.23s	remaining: 46.9s
264:	learn: 0.4319945	total: 4.25s	remaining: 46.9s
265:	learn: 0.4317483	total: 4.26s	remaining: 46.9s
266:	learn: 0.4316373	total: 4.28s	remaining: 46.9s
267:	learn: 0.4315517	total: 4.29s	remaining: 46.9s
268:	learn: 0.4311459	total: 4.31s	remaining: 46.8s
269:	learn: 0.4306961	total: 4.32s	remaining: 46.8s
270:	learn: 0.4302955	total: 4.34s	remaining: 46.8s
271:	learn: 0.4300722	total: 4.35s	remaining: 46.7s
272:	learn: 0.4297090	total: 4.37s	remaining: 46.7s
273:	learn: 0.4294841	total: 4.38s	remaining: 46.7s
274:	learn: 0.4290957	total: 4.4s	remaining: 46.7s
275:	learn: 0.4287435	total: 4.41s	remaining: 46.7s
276:	learn: 0.4284462	total: 4.43s	remaining: 46.6s
277:	learn: 0.4283594	total: 4.45s	remaining: 46.6s
278:	learn: 0.4282786	total: 4.46s	remaining: 46.6s
279:	learn: 0.4281188	total: 4.48s	remaining: 46.6s
280:	learn: 0.4277193	total: 4.49s	remaining: 46.6s
281:	learn: 0.4274089	total: 4.51s	remaining: 46.6s
282:	learn: 0.4272807	total: 4.52s	remaining: 46.5s
283:	learn: 0.4271780	total: 4.54s	remaining: 46.5s
284:	learn: 0.4269945	total: 4.55s	remaining: 46.5s
285:	learn: 0.4268604	total: 4.57s	remaining: 46.5s
286:	learn: 0.4266311	total: 4.58s	remaining: 46.4s
287:	learn: 0.4264801	total: 4.6s	remaining: 46.4s
288:	learn: 0.4263004	total: 4.61s	remaining: 46.4s
289:	learn: 0.4262200	total: 4.63s	remaining: 46.3s
290:	learn: 0.4259170	total: 4.64s	remaining: 46.3s
291:	learn: 0.4254789	total: 4.66s	remaining: 46.3s
292:	learn: 0.4252750	total: 4.68s	remaining: 46.3s
293:	learn: 0.4252319	total: 4.68s	remaining: 46.2s
294:	learn: 0.4251756	total: 4.7s	remaining: 46.1s
295:	learn: 0.4248947	total: 4.71s	remaining: 46.1s
296:	learn: 0.4245008	total: 4.72s	remaining: 46.1s
297:	learn: 0.4244617	total: 4.73s	remaining: 46s
298:	learn: 0.4243168	total: 4.75s	remaining: 46s
299:	learn: 0.4240530	total: 4.77s	remaining: 46s
300:	learn: 0.4240053	total: 4.79s	remaining: 46.1s
301:	learn: 0.4239563	total: 4.81s	remaining: 46s
302:	learn: 0.4234242	total: 4.82s	remaining: 46s
303:	learn: 0.4233744	total: 4.84s	remaining: 46s
304:	learn: 0.4233382	total: 4.84s	remaining: 45.9s
305:	learn: 0.4232712	total: 4.86s	remaining: 45.8s
306:	learn: 0.4231642	total: 4.87s	remaining: 45.8s
307:	learn: 0.4231248	total: 4.89s	remaining: 45.8s
308:	learn: 0.4230485	total: 4.91s	remaining: 45.8s
309:	learn: 0.4229610	total: 4.92s	remaining: 45.8s
310:	learn: 0.4226295	total: 4.94s	remaining: 45.8s
311:	learn: 0.4225088	total: 4.95s	remaining: 45.7s
312:	learn: 0.4224563	total: 4.97s	remaining: 45.7s
313:	learn: 0.4220793	total: 4.98s	remaining: 45.7s
314:	learn: 0.4220234	total: 5s	remaining: 45.7s
315:	learn: 0.4218115	total: 5.01s	remaining: 45.6s
316:	learn: 0.4217416	total: 5.03s	remaining: 45.6s
317:	learn: 0.4216244	total: 5.04s	remaining: 45.6s
318:	learn: 0.4215594	total: 5.06s	remaining: 45.6s
319:	learn: 0.4215134	total: 5.07s	remaining: 45.5s
320:	learn: 0.4212213	total: 5.09s	remaining: 45.5s
321:	learn: 0.4211950	total: 5.09s	remaining: 45.4s
322:	learn: 0.4210412	total: 5.11s	remaining: 45.4s
323:	learn: 0.4208197	total: 5.13s	remaining: 45.4s
324:	learn: 0.4207084	total: 5.14s	remaining: 45.4s
325:	learn: 0.4206224	total: 5.16s	remaining: 45.4s
326:	learn: 0.4205544	total: 5.17s	remaining: 45.4s
327:	learn: 0.4202098	total: 5.19s	remaining: 45.3s
328:	learn: 0.4200587	total: 5.2s	remaining: 45.3s
329:	learn: 0.4198130	total: 5.22s	remaining: 45.3s
330:	learn: 0.4196175	total: 5.24s	remaining: 45.3s
331:	learn: 0.4195645	total: 5.25s	remaining: 45.3s
332:	learn: 0.4194379	total: 5.27s	remaining: 45.3s
333:	learn: 0.4193438	total: 5.28s	remaining: 45.2s
334:	learn: 0.4192819	total: 5.3s	remaining: 45.2s
335:	learn: 0.4192481	total: 5.31s	remaining: 45.2s
336:	learn: 0.4190514	total: 5.33s	remaining: 45.2s
337:	learn: 0.4189727	total: 5.34s	remaining: 45.2s
338:	learn: 0.4186638	total: 5.36s	remaining: 45.1s
339:	learn: 0.4185190	total: 5.38s	remaining: 45.1s
340:	learn: 0.4181922	total: 5.39s	remaining: 45.1s
341:	learn: 0.4181093	total: 5.41s	remaining: 45.1s
342:	learn: 0.4180040	total: 5.42s	remaining: 45.1s
343:	learn: 0.4179386	total: 5.44s	remaining: 45s
344:	learn: 0.4178807	total: 5.45s	remaining: 45s
345:	learn: 0.4176811	total: 5.47s	remaining: 45s
346:	learn: 0.4176237	total: 5.48s	remaining: 45s
347:	learn: 0.4175720	total: 5.5s	remaining: 45s
348:	learn: 0.4174422	total: 5.52s	remaining: 45s
349:	learn: 0.4171359	total: 5.53s	remaining: 45s
350:	learn: 0.4170580	total: 5.55s	remaining: 44.9s
351:	learn: 0.4170240	total: 5.56s	remaining: 44.9s
352:	learn: 0.4169749	total: 5.58s	remaining: 44.9s
353:	learn: 0.4168916	total: 5.59s	remaining: 44.9s
354:	learn: 0.4168568	total: 5.61s	remaining: 44.8s
355:	learn: 0.4168181	total: 5.62s	remaining: 44.8s
356:	learn: 0.4167720	total: 5.64s	remaining: 44.8s
357:	learn: 0.4165828	total: 5.65s	remaining: 44.8s
358:	learn: 0.4165448	total: 5.67s	remaining: 44.7s
359:	learn: 0.4163383	total: 5.68s	remaining: 44.7s
360:	learn: 0.4163235	total: 5.68s	remaining: 44.6s
361:	learn: 0.4163064	total: 5.69s	remaining: 44.5s
362:	learn: 0.4162728	total: 5.7s	remaining: 44.5s
363:	learn: 0.4162452	total: 5.72s	remaining: 44.5s
364:	learn: 0.4162107	total: 5.73s	remaining: 44.4s
365:	learn: 0.4161758	total: 5.75s	remaining: 44.4s